### ISSUE TITLE
[oauth] and [json] don't create on some systems

### ISSUE THREAD

**Issue by 60-hz** [residuum/PuRestJson#49]
[oauth] and [json] are only working in 64bit pure data. Would be nice to be able to load them on a 32bit puredata instance as well so they can be usable along with many old libraries pd (gem etc...)

**Comment by residuum** [comment]
Which OS are you referring to? Where did you download it?

**Comment by mrpropre** [comment]
OSX 10.9, PurestJson 2.4.2 deken version

**Comment by residuum** [comment]
This is related to the build script, because the build script downloads and installs dependencies via homebrew, and not all libraries are available with 32 bit (see https://travis-ci.org/residuum/PuRestJson/jobs/372793900 lines 2363ff).

Maybe you could assist in creating universal packages for json-c and liboauth, as these are the culprits here.

**Comment by residuum** [comment]
Should be fixed with 2.0.0
